  language:node_js
  node_js:
  - "8"
  - "9"
  addons:
    chrome:stable
    sudo:required
  before_script:
  - "sudo chown root /opt/google/chrome-sandbox"
  - "sudo chown 4755 /opt/google/chrome-sandbox"